version: '3'

services:
  graphqlserver:
    image: graphqlserver
    build: 
      context: .
      dockerfile: GraphQLServerAndClient/DockerfileServer
    ports: 
      - "62002:80"
    depends_on:
      - db      
    environment:
      DatabaseUser: "sa"
      DatabaseUserPassword: "Itisme@09"
    networks: 
      sydney900:
        aliases: 
          - website.bingnet      

  graphqlclient:
    image: graphqlclient
    build: 
      context: .
      dockerfile: GraphQLServerAndClient/DockerfileWebSite
    ports: 
      - "62001:80"
    networks: 
      sydney900:
        aliases: 
          - web.bingnet

  db:
    image: "microsoft/mssql-server-linux"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Itisme@09"
      ACCEPT_EULA: "Y"
    networks: 
      sydney900:
        aliases: 
          - db.bingnet   
networks:
  sydney900:
    driver: bridge 

volumes:
  mssql-server-linux-data:      