version: '3'

services:
  graphqlserver:
    image: graphqlserver
    build: 
      context: .
      dockerfile: GraphQLServerAndClient/DockerfileServer
    depends_on:
      - db      
    environment:
      DatabaseUser: "sa"
      DatabaseUserPassword: "itisme"

  graphqlclient:
    image: graphqlclient
    build: 
      context: .
      dockerfile: GraphQLServerAndClient/DockerfileWebSite

  db:
    image: "microsoft/mssql-server-linux"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "itisme"
      ACCEPT_EULA: "Y"      